### ISSUE TITLE
Error on start in MAC

### ISSUE THREAD

**Issue by ciclanoio** [iam-mhaseeb/Python-Scrapy-Email-Phone-Number-Crawler#2]
Enter your query: phone radio
2018-11-11 11:39:32 [scrapy.core.engine] ERROR: Error while obtaining start requests
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/scrapy/core/engine.py", line 127, in _next_request
    request = next(slot.start_requests)
  File "/Users/mauriciocastro/Documents/GitHub/Python-Scrapy-Email-Phone-Number-Crawler/emailcrawler/spiders/emailspider.py", line 13, in start_requests
    query = input("Enter your query: ")
  File "<string>", line 1
    phone radio
            ^
SyntaxError: invalid syntax
2018-11-11 11:39:32 [scrapy.core.engine] INFO: Closing spider (finished)
2018-11-11 11:39:32 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'finish_reason': 'finished',
 'finish_time': datetime.datetime(2018, 11, 11, 13, 39, 32, 966561),
 'log_count/DEBUG': 1,
 'log_count/ERROR': 1,
 'log_count/INFO': 7,
 'memusage/max': 50974720,
 'memusage/startup': 50974720,
 'start_time': datetime.datetime(2018, 11, 11, 13, 39, 26, 686559)}
2018-11-11 11:39:32 [scrapy.core.engine] INFO: Spider closed (finished)

**Comment by ciclanoio** [comment]
using 'keyword'  works, but any result

Enter your query: 'webradio gospel'
2018-11-11 11:46:40 [scrapy.downloadermiddlewares.redirect] DEBUG: Redirecting (301) to <GET http://www.google.com/search?q=webradio%20gospel> from <GET http://google.com/search?q=webradio%20gospel>
2018-11-11 11:46:44 [scrapy.downloadermiddlewares.redirect] DEBUG: Redirecting (302) to <GET https://www.google.com/search?q=webradio%20gospel&gws_rd=ssl> from <GET http://www.google.com/search?q=webradio%20gospel>
2018-11-11 11:46:49 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.google.com/search?q=webradio%20gospel&gws_rd=ssl> (referer: None)
2018-11-11 11:46:49 [scrapy.core.engine] INFO: Closing spider (finished)
2018-11-11 11:46:49 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 1272,
 'downloader/request_count': 3,
 'downloader/request_method_count/GET': 3,
 'downloader/response_bytes': 94268,
 'downloader/response_count': 3,
 'downloader/response_status_count/200': 1,
 'downloader/response_status_count/301': 1,
 'downloader/response_status_count/302': 1,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2018, 11, 11, 13, 46, 49, 742433),
 'log_count/DEBUG': 4,
 'log_count/INFO': 7,
 'memusage/max': 50876416,
 'memusage/startup': 50876416,
 'response_received_count': 1,
 'scheduler/dequeued': 3,
 'scheduler/dequeued/memory': 3,
 'scheduler/enqueued': 3,
 'scheduler/enqueued/memory': 3,
 'start_time': datetime.datetime(2018, 11, 11, 13, 46, 27, 334668)}
2018-11-11 11:46:49 [scrapy.core.engine] INFO: Spider closed (finished)

**Comment by iam-mhaseeb** [comment]
302 results are not handled yet. These will be handled in next update.

**Comment by iam-mhaseeb** [comment]
Fixed
